### ISSUE TITLE
Missing semicolon on line 361

### ISSUE THREAD

**Issue by ssmit1986** [vincent-picaud/MathematicaStan#2]
Small remark: on line 361 of CmdStan.m (current master version) there is a semicolon missing after this block of code:

`If[FileExtension[outputFile]=="",
  outputFile=outputFile<>".csv";
]`

The code does actually seem to work as intended because this `If` statement is multiplied with the next one, so they still both evaluate. But it's still a syntax error.

**Comment by vincent-picaud** [comment]
I am really sorry for the delay ssmit1986, I just realized I had not subscribed and I just read your message now. You are right, I will fix that tomorrow.
I think that this package need an update. Originaly it has been developed to run under MMA v8!
It's time to update to MMA 10.
Best

**Comment by ssmit1986** [comment]
We're actually already at version 11.3 and soon 12 ;). From the looks of it, though, I don't think there should be many compatibility issues with the newer versions. If I ever have time, I plan to take a better look at the code here and see if I do something constructive.

**Comment by vincent-picaud** [comment]
On my side I think compatibility is ok (I am currently using MMA v11). 
However I think that introducing Association[] for input/output data will be a big improvement concerning ease of use. Moreover I have to improve RData export: currently it only supports 0,1 and 2 dim arrays: would be nice to extend that for higher dimensions.

**Comment by vincent-picaud** [comment]
Are you under Linux? Mac or Windows? On my side I am only using Linux

**Comment by ssmit1986** [comment]
I generally use Windows, so that should give us some more coverage for checking platform compatibility. And I totally agree with using Associations where possible. That would be a big convenience.

**Comment by vincent-picaud** [comment]
Yes, that's perfect and that would be a valuable help.
I hope that I will be able to update this package October/November.
If you have idea or contribution to suggest, they are welcome :)

**Comment by vincent-picaud** [comment]
Fixed , thanks.
