### ISSUE TITLE
Any chance of a tutorial on non-parametric, multidimensional, error-in-variables regression?

### ISSUE THREAD

**Issue by sgbaird** [vincent-picaud/MathematicaStan#3]
Inputs: x1, x1_std, x2, x2_std, x3, x3_std, ... y, y_std

**Comment by vincent-picaud** [comment]
Thank you for your interest.
Unfortunately ad because I lack of time, I was not thinking to add new tutorials right now. 
However maybe I can help you to use MathematicaStan for a peculiar model. 
Did you read https://mc-stan.org/docs/2_18/stan-users-guide/bayesian-measurement-error-model.html ?

**Comment by sgbaird** [comment]
Hi @vincent-picaud, thanks for your response. I posted a [related stack exchange question](https://stats.stackexchange.com/questions/515864/what-functions-packages-in-python-matlab-mathematica-or-r-implement-error-in) as well as on the [stan discourse page](https://discourse.mc-stan.org/t/non-parametric-multidimensional-regression-with-measurement-error-in-predictors-and-responses/21528). I have been referencing the link you shared as well as the [Gaussian process regression section](https://mc-stan.org/docs/2_22/stan-users-guide/fit-gp-section.html). My impression is that I need to find a good way to follow the same conversion from [1] --> [2] for [3]:

## [[1](https://mc-stan.org/docs/2_22/stan-users-guide/bayesian-measurement-error-model.html)]
```stan
data {
  int<lower=0> N;       // number of cases
  vector[N] x;          // predictor (covariate)
  vector[N] y;          // outcome (variate)
}
parameters {
  real alpha;           // intercept
  real beta;            // slope
  real<lower=0> sigma;  // outcome noise
}
model {
  y ~ normal(alpha + beta * x, sigma);
  alpha ~ normal(0, 10);
  beta ~ normal(0, 10);
  sigma ~ cauchy(0, 5);
}
```

## [[2](https://mc-stan.org/docs/2_22/stan-users-guide/bayesian-measurement-error-model.html)]
```stan
data {
  ...
  real x_meas[N];     // measurement of x
  real<lower=0> tau;  // measurement noise
}
parameters {
  real x[N];          // unknown true value
  real mu_x;          // prior location
  real sigma_x;       // prior scale
  ...
}
model {
  x ~ normal(mu_x, sigma_x);  // prior
  x_meas ~ normal(x, tau);    // measurement model
  y ~ normal(alpha + beta * x, sigma);
  ...
}
```

## [[3](https://mc-stan.org/docs/2_22/stan-users-guide/fit-gp-section.html)]
```stan
data {
  int<lower=1> N;
  real x[N];
  vector[N] y;
}
transformed data {
  vector[N] mu = rep_vector(0, N);
}
parameters {
  real<lower=0> rho;
  real<lower=0> alpha;
  real<lower=0> sigma;
}
model {
  matrix[N, N] L_K;
  matrix[N, N] K = cov_exp_quad(x, alpha, rho);
  real sq_sigma = square(sigma);

  // diagonal elements
  for (n in 1:N)
    K[n, n] = K[n, n] + sq_sigma;

  L_K = cholesky_decompose(K);

  rho ~ inv_gamma(5, 5);
  alpha ~ std_normal();
  sigma ~ std_normal();

  y ~ multi_normal_cholesky(mu, L_K);
}
```

Any help is much appreciated. If I can get it working, I'd be more than happy to write a tutorial for this and send in a pull request.

**Comment by sgbaird** [comment]
Maybe worth mentioning https://botorch.org/tutorials/risk_averse_bo_with_input_perturbations. I'm fine with this being closed.

**Comment by vincent-picaud** [comment]
I hope I haven't offended you, @sgbaird. The post was inactive for over a year, and I also have to update this Mathematica package.
I don't know if you are using it ?

**Comment by bob-carpenter** [comment]
@sgbaird---I didn't notice this issue from before, but it sounds like you're asking for a case study.  Putting that in `stan-dev/docs` is probably the righ thing to do.  It shouldn't go here as this isa bout Mathematica-specific issues.

I'm not sure what non-parametric error-in-variables means.  There's a chapter on measurement error models in the user's guide, but I'm not sure if it talks about measurement error for the predictors, the outcomes, both, or neither, in a regression context.  Please feel free to make a very specific request, and if you know how to do it yourself, to just submit a doc PR.

**Comment by sgbaird** [comment]
> I hope I haven't offended you, @sgbaird. The post was inactive for over a year, and I also have to update this Mathematica package.
> I don't know if you are using it ?

@vincent-picaud not at all offended 😄. When I looked into Stan, I didn't have the bandwidth at the time to learn it. At some point, I may return to Stan, but it will probably be in Python as I've transitioned to Python as my primary coding language (I still use Mathematica, but less frequently). 



> @sgbaird---I didn't notice this issue from before, but it sounds like you're asking for a case study. Putting that in `stan-dev/docs` is probably the righ thing to do. It shouldn't go here as this isa bout Mathematica-specific issues.

Good point!

> I'm not sure what non-parametric error-in-variables means. There's a chapter on measurement error models in the user's guide, but I'm not sure if it talks about measurement error for the predictors, the outcomes, both, or neither, in a regression context. Please feel free to make a very specific request, and if you know how to do it yourself, to just submit a doc PR.

This largely stems from a machine-learning / data science perspective + wetlab experimentation. You have many tunable input parameters, some of which may be noisy, and some performance property that you want to optimize, the measurement of which is also subject to noise. By non-parametric error-in-variables I was intending to convey the concept of when you have existing training data and build a model as a function of the predictors to predict some outcome.

Thanks for the context! I don't know how to do this with Stan yet.
